version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: employee-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employee_db
    ports:
      - "5455:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  config-service:
    build: ./empl-config-server
    container_name: empl-config-server
    ports:
      - "8888:8888"
    networks:
      - backend
    environment:
      SPRING_PROFILES_ACTIVE: backend

  employee-service:
    build: ./empl-service
    container_name: empl-service
    depends_on:
      - postgres
      - config-service
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      SPRING_PROFILES_ACTIVE: backend
      SPRING_CLOUD_CONFIG_URI: http://config-service:8888

  api-gateway:
    build: ./empl-gateway
    container_name: empl-gateway
    depends_on:
      - config-service
      - employee-service
    ports:
      - "8081:8081"
    networks:
      - backend
    environment:
      SPRING_PROFILES_ACTIVE: backend
      SPRING_CLOUD_CONFIG_URI: http://config-service:8888

volumes:
  postgres-data:

networks:
  backend:
