version: '3.8'

services:
  db:
    image: postgres:16
    container_name: employee-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employee_db
    ports:
      - "5455:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - employee-network

volumes:
  postgres-data:

networks:
  employee-network:
    driver: bridge
